apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ysa6grv8i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ysa6grv8i-go 
  name: ysa6grv8i-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ysa6grv8i-go 
